apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          ports:
            - containerPort: 6333
          volumeMounts:
            - mountPath: /qdrant/storage
              name: qdrant-data
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: qdrant-data
          persistentVolumeClaim:
            claimName: qdrant-storage
