apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: staging
spec:
  selector:
    app: qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
  type: ClusterIP  #only accessible from inside the cluster