apiVersion: apps/v1
kind: Deployment
metadata:
  name: phi2-ollama
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phi2-ollama
  template:
    metadata:
      labels:
        app: phi2-ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          args: ["serve"]
          ports:
            - containerPort: 11434
          env:
            - name: OLLAMA_CONTEXT_LENGTH
              value: "2048"
            - name: OLLAMA_KEEP_ALIVE
              value: "10m"
            - name: OLLAMA_MAX_LOADED_MODELS
              value: "1"
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-pvc
