apiVersion: apps/v1
kind: Deployment
metadata:
  name: phi2-ollama
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phi2-ollama
  template:
    metadata:
      labels:
        app: phi2-ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          args: ["serve"]
          ports:
            - containerPort: 11434
          env:
            - name: OLLAMA_CONTEXT_LENGTH
              value: "2048"
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      volumes:
        - name: ollama-data
          emptyDir: {}  # Replace with a PVC if needed
