apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-preload-phi2
  namespace: staging
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        job-name: ollama-preload-phi2
    spec:
      restartPolicy: OnFailure
      containers:
        - name: preload
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for Ollama to be ready..."
              until curl -s http://phi2:80/api/status; do sleep 2; done
              echo "Pulling Phi 2.7B model..."
              curl -X POST http://phi2:80/api/pull -H "Content-Type: application/json" -d '{"name": "phi:2.7b"}'