services:
  ingestor:
    build: .
    ports:
      - "8000:8000"
    container_name: searchvault-ingestor
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_URL=http://host.docker.internal:11434/api/chat
      - LLM_PROVIDER=openai
      - OPENAI_API_KEY=
    networks:
      - searchvault-net

networks:
  searchvault-net:
    external: true