services:
  ingestor:
    build: .
    ports:
      - "8000:8000"
    container_name: searchvault-ingestor
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    networks:
      - searchvault-net

networks:
  searchvault-net:
    external: true