apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestor-env
  namespace: staging
data:
  OLLAMA_URL: "http://65.109.81.99:11434/api/chat"
  QDRANT_HOST: "qdrant.staging.svc.cluster.local"
  QDRANT_PORT: "6333"
  LLM_PROVIDER: "local"
  OPENAI_API_KEY: "OPEN_API_KEY"