apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchvault-ingestor
  labels:
    app: searchvault-ingestor
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchvault-ingestor
  template:
    metadata:
      labels:
        app: searchvault-ingestor
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - name: searchvault-ingestor
          image: ghcr.io/alphametic-services-and-technologies/searchvault-ingestor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: ingestor-env
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
