apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestor
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestor
  template:
    metadata:
      labels:
        app: ingestor
    spec:
      containers:
        - name: ingestor
          image: ghcr.io/alphametic-services-and-technologies/searchvault-ingestor:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: ingestor-env
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
