apiVersion: v1
kind: Service
metadata:
  name: ingestor
  namespace: staging
spec:
  selector:
    app: ingestor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP  #only accessible from inside the cluster